name: trivy_with_comment_and_branch
on:
  pull_request:
    types: [opened]
    branches:
      - develop
  pull_request_review_comment:
    types: [created]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check PR for specific comment and branch
        id: check_pr
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'develop' && contains(github.event.pull_request.body, 'Run Tests') }}
        run: exit 0

      - name: Run Trivy vulnerability scanner in repo mode
        if: ${{ steps.check_pr.outcome == 'success' }}
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        if: ${{ steps.check_pr.outcome == 'success' }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
